apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 200Mi
 
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dev-ingress
  namespace: hello
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: app2.cbradford1.nkn.uidaho.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80
---
